### ISSUE TITLE
Clarify license of this repository

### ISSUE THREAD

**Issue by kpengboy** [AQEMU/aqemu#1]
There is a COPYING file which contains a GPLv2 license and a LICENSE file which contains an MIT license. What is the real license?

Was the extra LICENSE file added by mistake, or is the intent that some new code is being licensed under MIT? (Note that the license of the existing code is GPL and cannot simply be changed without the consent of all copyright holders.)

**Comment by GermanAizek** [comment]
Fixed in this commit https://github.com/AQEMU/aqemu/commit/b671cf35f2c3b1ee5b0786208ced407fd941128e
