### ISSUE TITLE
Changing the license to GPLv3+

### ISSUE THREAD

**Issue by kpengboy** [AQEMU/aqemu#3]
In https://github.com/tobimensch/aqemu/issues/73 there was an initiative to change the license from GPLv2 to GPLv3-or-later. All of the contributors to that repository have already given their permission to relicense the codebase.

@GermanAizek would you be willing to accept a change that would relicense this fork?

@nikitamos, @gogoprog, and @coolshou: given that you three have contributed to this fork, would you consent to such a license change?

**Comment by gogoprog** [comment]
Hi,

I do consent to this change.

**Comment by coolshou** [comment]
Sure, I agree to change license to GPLv3+.

**Comment by GermanAizek** [comment]
@kpengboy @nikitamos @gogoprog @coolshou
Im changed license to GPLv3 https://github.com/AQEMU/aqemu/commit/db1ff4efe68526b8f1ec97a4f8615cd97f6fa55d
Now I'm going to be more actively contributed in AQEMU.

**Comment by kpengboy** [comment]
Wait though, did @nikitamos approve this change?
